export const userConstants = {
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

    FORGOT_PASSWORD_REQUEST: "USERS_FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "USERS_FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE: "USERS_FORGOT_PASSWORD_FAILURE",

    RESET_PASSWORD_REQUEST: "USERS_RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "USERS_RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "USERS_RESET_PASSWORD_FAILURE",

    ACTIVEACCOUNT_REQUEST: "USERS_ACTIVEACCCOUNT_REQUEST",
    ACTIVEACCOUNT_SUCCESS: "USERS_ACTIVEACCCOUNT_SUCCESS",
    ACTIVEACCOUNT_FAILURE: "USERS_ACTIVEACCCOUNT_FAILURE",

    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    LOGOUT: "USERS_LOGOUT",

    IS_LOGIN: "IS_LOGIN",

    GETALL_REQUEST: "USERS_GETALL_REQUEST",
    GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
    GETALL_FAILURE: "USERS_GETALL_FAILURE",

    UPDATE_REQUEST: "USERS_UPDATE_REQUEST",
    UPDATE_SUCCESS: "USERS_UPDATE_SUCCESS",
    UPDATE_FAILURE: "USERS_UPDATE_FAILURE",

    DELETE_REQUEST: "USERS_DELETE_REQUEST",
    DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
    DELETE_FAILURE: "USERS_DELETE_FAILURE",

    GET_DETAIL_REQUEST: "USERS_GET_DETAIL_REQUEST",
    GET_DETAIL_SUCCESS: "USERS_GET_DETAIL_SUCCESS",
    GET_DETAIL_FAILURE: "USERS_GET_DETAIL_FAILURE",

    UPDATE_DETAIL_REQUEST: "USERS_UPDATE_DETAIL_REQUEST",
    UPDATED_ETAIL_SUCCESS: "USERS_UPDATE_DETAIL_SUCCESS",
    UPDATED_ETAIL_FAILURE: "USERS_UPDATE_DETAIL_FAILURE",
};
